# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'userDefaults' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for userDefaults

pod 'YYModel'

  target 'userDefaultsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'userDefaultsUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
